### PR TITLE
Implement RTF Export

### PR DESCRIPTION
**Pull request by AntonyBoucher**
Basic export to RTF, with suitable formatting for titles, paragraphs, quotes and code blocks. It supports Unicode, and escapes special characters when appropriate. The form does not prompt for any additional metadata.

### CODE REVIEW

**Comment by TorstenDittmann** [comment]
Awesome work!

Gonna review it this evening and link #25 for visibility.

**Comment by TorstenDittmann** [comment]
@AntonyBoucher Merged 🥳 

Really nice work and these contributions are very appreciated! Especially because my knowledge of Unicode & co is very limited.

Feel free to create an issue in GitHub when you are working on something specific, so we won't work on the same thing 🙂

Next task for me will be a contributors section inside OmniaWrite 😉

**Comment by AntonyBoucher** [comment]
Thanks Torsten! My name in a `CONTRIBUTORS` file inside the source repository would be good enough for me 😊

I like your suggestion to use Github issues for coordination. Would you consider writing it down into a `CONTRIBUTING` file?

**Comment by TorstenDittmann** [comment]
Writing a `CONTRIBUTION` file sounds like a great idea!

Gonna write one down over the week including the quirks, structure & co of this repo 👍

**Pull request merged**
