### PR TITLE
Added Finnish translation

### PR DESCRIPTION
**Pull request by minna-xD**
Added fi.json and the language entry as requested

### CODE REVIEW

**Comment by minna-xD** [comment]
My apologies. I followed the Hacktoberfest instruction video by Digital Ocean but it failed to mention that I should've refreshed my fork from upstream before creating a PR. I tried to refresh (&merge) but I'm not sure I'll resolve the conflicts correctly so I'd rather not risk messing it up more... Let me know if there's something I need to do!

**Comment by TorstenDittmann** [comment]
I resolved everything 😉

**Comment by minna-xD** [comment]
Thank you!!

**Comment by TorstenDittmann** [comment]
@allcontributors please add @minna-xD for translation

**Pull request merged**
