### PR TITLE
Added the BrowserSupport Modal #40

### PR DESCRIPTION
**Pull request by syentix**
I added the Modal UI and the the functions needed to work it out. I guessed on the capacitor check though, since I didn't find anything and had no way to test it.

### CODE REVIEW

**Comment by TorstenDittmann** [comment]
Looks good so far, except a few things:

Every Browser that is not one of these:
- Chromium based
- Firefox
- Safari/WebKit
- Electron
- Capacitor

So, also Chrome users should'nt receive this message. This is mainly targeted for people using some browsers like the old Edge & co.

Also the current `dev` branch needs to be forked, since we have replaced moment-js with date-fns in there. So take a look around [here ](https://github.com/TorstenDittmann/OmniaWrite/blob/dev/src/utils.js#L146) to grab a date-fns instance 🙂 

Amazing work so far!

**Comment by syentix** [comment]
Hope this is fine now

**Comment by TorstenDittmann** [comment]
Target branch has to be dev as well 🙂

**Comment by syentix** [comment]
I definetly messed up some stuff on my half I'm so sorry!

**Comment by TorstenDittmann** [comment]
Yeah, there is definetely something messed up 😄 

I would recommend creating a new branch from `dev` and re-add the changes by hand 😉

**Pull request closed without merging**
